<script type="text/javascript"  >
	var width;
	var height;
	var currPopupText;//Text of the the popup

	// TODO verify how this variable works for other layers and see
	// from where we can obtain the current elevation.
	var elevation = 0;

	//Should contain the selected start date and is used to obtain punctual
	// data from the temporal data.
	var startDate;

	//Creates 100 layer objects
	for (var i = 0; i < 100; i++) {
		eval("var layer" + i);
	}

	function initOl3() {
		
		<jsp:include page="../common/JS/mapDisplay/Popup.js" />
			
		var bounds = mapConfig.mapBounds;
		var extent = mapConfig.restrictedExtent;
		var maxRes = mapConfig.maxResolution;
		var minRes = mapConfig.minResolution;
		//extent
		var zoomLevels = mapConfig.numZoomLevels;
		
        var strCenter = mapConfig.mapcenter.split(",");

        var lat = 0;
        var lon = 0;
        if( strCenter[0].split("=")[0].toLowerCase() === "lat"){
            lat = Number(strCenter[0].split("=")[1]);
            lon = Number(strCenter[1].split("=")[1]);
        }else{
            lat = Number(strCenter[1].split("=")[1]);
            lon = Number(strCenter[0].split("=")[1]);
        }

        var defCenter;

        if(_map_bk_layer === "wms"){
            //If the default projection is not 4326 then we need to transform 
            // the projections to the default map projection
            if(_map_projection !== 'EPSG:4326'){
                defCenter= ol.proj.transform([lon, lat], 'EPSG:4326', _map_projection);
            }else{
                defCenter= [lon,lat];
            }
        }else{
            if(_map_bk_layer === "osm"){
                _map_projection = 'EPSG:3857';//Force projection for osm background layer
                defCenter= ol.proj.transform([lon, lat], 'EPSG:4326', _map_projection);
            }
        }

		ol3view = new ol.View2D({
                projection: _map_projection,
                center: defCenter,
                zoom: mapConfig.zoom,
                });
		
		/**
		 * Create the map.
		 */
		map = new ol.Map({
			overlays: [ol_popup], //Overlay used for popup
			target: 'map', // Define 'div' that contains the map
            renderers: [ol.RendererHint.CANVAS, ol.RendererHint.DOM],
			view: ol3view
		});

        //Adds a zoom slider on the map
        zoomslider = new ol.control.ZoomSlider();
        map.addControl(zoomslider);
		
		//This openLayerConfig is generated by the java file OpenLayersManager.java 
		//it loads all the layers that are needed for the map. 
	${openLayerConfig}
		}
</script>
